#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other compatible shell such as ksh or
#       bash, then use that shell instead.
#
#   (2) Runs this script from within a shell by invoking with that shell, and then
#       the parenthesized local variable declarations will NOT be reset.
#       Thus, if you have a personal init script or set a bash function for
#       'gradle', this will prevent the Spring from resetting it.
#       (See also the post_process_gradle_execution function tuning.)
#
#   Trick: If you use "bash -x" with this bourne shell script, you'll see
#   +set debug mode messages without having to modify this script (only useful
#   with "set -x" implied with 'sh -x' as well)
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls -ld "$PRG"
    PRG=`readlink "$PRG"`
done
PRG_DIR=`dirname "$PRG"`
APP_HOME=`cd "$PRG_DIR" && pwd -P` || exit 1

appname=`basename "$0"`
APP_PATH="$APP_HOME/$appname"

# Add a user-defined CLASSPATH environment variable onto the JVM submission in UNIX( type
if [ ! -z "$CLASSPATH" ] ; then
  CLASSPATH="$CLASSPATH:."
else
  CLASSPATH="."
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if expr "$OSTYPE" : 'cygwin\|msys' > /dev/null; then
    APP_HOME=`( cd "$APP_HOME" && pwd -W )`
    CLASSPATH=`( cd "$CLASSPATH" && pwd -W )`
    JAVACMD=`which java.exe`
else
    JAVACMD=`which java`
fi

if [ ! -x "$JAVACMD" ] ; then
    echo "Error: JAVA_HOME is not defined correctly." >&2
    echo "  We cannot execute $JAVACMD" >&2
    exit 1
fi

if [ -z "$JAVA_HOME" ] ; then
    echo "Warning: JAVA_HOME environment variable is not set."
fi

LOCK_DIR=".gradle"
if [ ! -d "$LOCK_DIR" ] ; then
    mkdir -p "$LOCK_DIR"
fi

exec "$JAVACMD" -server -XX:MaxMetaspaceSize=512m -XX:+UseG1GC $JAVA_OPTS -Dorg.gradle.appname="$appname" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
